### ISSUE TITLE
Shorten PR

### ISSUE THREAD

**Issue by jerone** [fregante/shorten-repo-url#18]
# Input
Should the following URLs be shortened:

* `https://github.com/sindresorhus/refined-github/pull/2229`
* `https://github.com/sindresorhus/refined-github/pull/2229/files`
* `https://github.com/sindresorhus/refined-github/pull/2229/commits`
* `https://github.com/sindresorhus/refined-github/pull/2229/commits/b8b9a3394d9aa667ad9c2576ff5fd381147c4960`, which is now shown as `b8b9a33`, losing the PR information.

# Expected
* `PR#2229`
* `PR#2229 (files)`
* `PR#2229 (commits)`
* `PR#2229 (commit ``b8b9a33``)`

**Comment by bfred-it** [comment]
The last example is not our fault, GitHub drops the PR info from the link itself so we can never display it that way
