### ISSUE TITLE
Inaccurate shortened links

### ISSUE THREAD

**Issue by sudo-suhas** [fregante/shorten-repo-url#9]
Consider the following url:

`https://github.com/sudo-suhas/webpack/blob/docs/init-develop/README.md#usage`. 

The branch in this case is actually `docs/init-develop`. If I run it through `shorten-repo-url`, I get this:

`'sudo-suhas/webpack:init-develop/README.md@<code>docs</code>#usage'` 

But it should have been this:

`'sudo-suhas/webpack:README.md@<code>docs/init-develop</code>#usage'`.

This probably cannot be handled but I am reporting it in case you can think of a way to handle it. Or it could be mentioned as a known limitation in the readme.

**Comment by bfred-it** [comment]
You’re right, the URL is anbiguous and can’t be correctly shortened without accessing the repo. You can ask GitHub to start escaping the slash in the branch name.

**Comment by bfred-it** [comment]
Closing because this has no solution
